table Query1
	lineageTag: b41e590f-3ca5-4571-b6dd-cba749bb4162

	measure 'Total Sales' = SUM(Query1[SalesAmount])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f9bb3d00-a525-47ac-acbb-c3dab54115ef

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Profit' = [Total Sales]-[Total Cost]
		lineageTag: d033c00a-3ba7-40e6-9494-61bc89202ce1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity Sold' = SUM(Query1[OrderQuantity])
		formatString: 0
		lineageTag: 52b0975f-55b2-4b33-aea3-fb4aeb80f52a

	measure 'Total Order Number' = COUNT(Query1[SalesOrderNumber])
		formatString: 0
		lineageTag: 34e9aba3-1633-4a57-b2dc-7b2bb390f8bd

	measure 'Sales YTD' = TOTALYTD([Total Sales], DateTable[Date])
		lineageTag: 6aa07aab-3a6d-4a09-a8d6-fe1bd4f936a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales PY YTD' = CALCULATE([Sales YTD], DATESYTD(SAMEPERIODLASTYEAR(DateTable[Date])))
		lineageTag: a98e3ddd-11db-4286-8e24-c0c32aed411b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Growth %' = DIVIDE([Sales YTD]-[Sales PY YTD],[Sales PY YTD],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 986eea22-9240-4ccf-a7cc-fda5f4f3e1a0

	measure 'Profit Margin %' = DIVIDE([Total Profit], [Total Sales], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0e81bcd4-ae4d-4070-a5c0-4ebe52ef3d55

	measure 'Total Cost' = SUMX(Query1, Query1[StandardCost] * Query1[OrderQuantity])
		lineageTag: f20e4bbc-2be7-4987-9790-f5941755644f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average OV' = [Total Sales] / DISTINCTCOUNT(Query1[SalesOrderNumber])
		lineageTag: 87bcc5d4-c61b-4948-ab33-32c09f7a6851

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distinct Products Sold' = DISTINCTCOUNT(Query1[CustomerKey])
		formatString: 0
		lineageTag: f56667bd-e2eb-4f5c-b1f5-31c857da298d

	measure 'Sales Change by Category' =
			
			VAR SalesThisYear = [Sales YTD]
			VAR SalesLastYear = [Sales PY YTD]
			RETURN
			SalesThisYear - SalesLastYear
		lineageTag: f5990725-c283-46cb-b555-ced5d27bb1f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesOrderNumber
		dataType: string
		lineageTag: 6b39d300-75df-46d5-b958-f9f1c498d65f
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: b85b4a78-ef1a-4330-ad1c-a5a628ed43e2
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: b4d8b5ea-5659-4ce4-bb70-00a9846c7988
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAmount
		dataType: double
		formatString: 0.00
		lineageTag: e1bfbb5b-fbf0-49ed-b88c-8fca99dc522d
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Query1","TableItemName":"SalesAmount (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column TaxAmt
		dataType: double
		lineageTag: 89b379f3-8439-4d37-91ac-16a3432d01fd
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Freight
		dataType: double
		lineageTag: 84aa4d81-53f1-45ef-8655-239fea9db842
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 4d13dba2-71b6-4ea6-b12b-8123431be947
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		isHidden
		lineageTag: 8b2eafab-7ca0-48a6-94ed-1953e9099805
		summarizeBy: none
		sourceColumn: FirstName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		isHidden
		lineageTag: 2551cba1-3536-4ae4-9688-18dc51a80621
		summarizeBy: none
		sourceColumn: LastName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: de01062c-1ccc-4f12-affc-51bd27982b24
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		isHidden
		lineageTag: 13f096ac-95ff-4a53-9103-34f7bde425c1
		summarizeBy: none
		sourceColumn: EmailAddress

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearlyIncome
		dataType: decimal
		lineageTag: d18e5f38-1e76-4937-ad2a-1c5f401f4c1e
		summarizeBy: sum
		sourceColumn: YearlyIncome

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Occupation
		dataType: string
		lineageTag: 1ded6f79-a947-4e1a-9008-4f783678123f
		summarizeBy: none
		sourceColumn: Occupation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Education
		dataType: string
		isHidden
		lineageTag: 06a2fc53-7fcb-402b-be7a-4d52f51ae668
		summarizeBy: none
		sourceColumn: Education

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 596abe61-3818-433a-94f9-3fe9c703ea77
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 3e333500-c2e0-4cdf-8326-ababbd54d5d2
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		isHidden
		lineageTag: 31c92a6c-adc7-4831-a2ba-f58f8bfafd3e
		summarizeBy: none
		sourceColumn: Color

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		isHidden
		lineageTag: a7265e61-73d9-4c0a-8650-6be2ce2f05b3
		summarizeBy: none
		sourceColumn: Size

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: double
		lineageTag: f385bf5b-2fce-48c8-b4a5-52679d771d49
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StandardCost
		dataType: double
		formatString: 0.00
		lineageTag: 10ca55c2-0731-49e6-838a-b2856d44340d
		summarizeBy: sum
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic

	column ProfitPerUnit
		dataType: double
		lineageTag: 38745cc9-1e42-48f0-8d8b-5a4bb8908d64
		summarizeBy: sum
		sourceColumn: ProfitPerUnit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Subcategory
		dataType: string
		lineageTag: 9c490376-7163-49d7-b7f1-b39ae14da3bb
		summarizeBy: none
		sourceColumn: Subcategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 68aaeb67-c74d-4a62-964d-2bb93cead2ff
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: string
		isHidden
		lineageTag: eb6d6eb3-3418-41a2-9f23-a92b4e9fbe79
		summarizeBy: none
		sourceColumn: DayOfWeek

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		isHidden
		lineageTag: 685e2cc3-a82b-4f08-aabb-3a737b48ae83
		summarizeBy: none
		sourceColumn: MonthName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: c8d91ee1-3c13-4606-b917-fc9c000e8ab4
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3089c132-c4e5-477b-af10-2d549a9a9a8d
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 5da836bb-2c34-4a1f-b06d-ef5ccf3aa59e
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: f83c1efb-82ed-4c2a-80c8-e625121182af
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		isHidden
		lineageTag: 2cbf20aa-6014-4bba-8848-d6a94ce64601
		summarizeBy: none
		sourceColumn: Group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerCountry
		dataType: string
		lineageTag: 7e09dd75-df93-48a1-a4ca-5dc97b5e9fe4
		summarizeBy: none
		sourceColumn: CustomerCountry

		annotation SummarizationSetBy = Automatic

	column CustomerState
		dataType: string
		lineageTag: 528fec6f-4f18-46d1-83b6-47859742d1a0
		summarizeBy: none
		sourceColumn: CustomerState

		annotation SummarizationSetBy = Automatic

	column CustomerCity
		dataType: string
		lineageTag: 4f5a9986-a15c-46fb-882d-c90ed6b7e0a6
		summarizeBy: none
		sourceColumn: CustomerCity

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e71d9d0d-9670-4cf1-b25e-4ffc4df87c10
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: abb0d088-7135-4d5e-ab94-91f14a7ea0b4
		summarizeBy: none
		sourceColumn: DueDate

		variation Variation
			isDefault
			relationship: 0583c455-7236-48f6-9e83-27a4514bb1eb
			defaultHierarchy: LocalDateTable_62699ae4-4c6d-41fa-b437-61a2a3b90f63.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: a9d892fe-de24-4537-888e-1c0c95ec3df3
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: cce53a14-e106-495b-924b-487488cdec5a
			defaultHierarchy: LocalDateTable_50fcc6ff-5c2a-4211-9f3b-5605511d2ba8.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FullDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 5bae3d4a-35a7-42e1-971a-5ca8e1bde69d
		summarizeBy: none
		sourceColumn: FullDate

		variation Variation
			isDefault
			relationship: 9d4b1e0c-bcea-4757-a1d3-45a0fc2eb15e
			defaultHierarchy: LocalDateTable_20a8ec80-e5b3-489f-9ac0-aa129ffb7885.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'SalesAmount (bins)' =
			IF(
				ISBLANK('Query1'[SalesAmount]),
				BLANK(),
				IF(
					'Query1'[SalesAmount] >= 0,
					ROUNDDOWN('Query1'[SalesAmount] / 500, 0) * 500,
					ROUNDUP('Query1'[SalesAmount] / 500, 0) * 500
				)
			)
		formatString: 0.00
		lineageTag: a03c9248-cb56-4b55-a8b0-275fb5bf3123
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Query1"
				          }
				        },
				        "Property": "SalesAmount"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 500.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"q","Entity":"Query1"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"q"}},"Property":"SalesAmount"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"q"}},"Property":"SalesAmount"}},"Size":500.0}}}}

		annotation SummarizationSetBy = Automatic

	partition Query1 = m
		mode: import
		source =
				let
				    Source = Sql.Database("(localdb)\MSSQLLocalDB", "AdventureWorksDW2019", [Query="SELECT#(lf)    -- 1. KEY SALES METRICS from the Fact Table#(lf)    fis.SalesOrderNumber,#(lf)    fis.OrderDate,#(lf)    fis.DueDate,#(lf)    fis.ShipDate,#(lf)    fis.OrderQuantity,#(lf)    fis.UnitPrice,#(lf)    fis.SalesAmount,#(lf)    fis.TaxAmt,#(lf)    fis.Freight,#(lf)    #(lf)    -- 2. CUSTOMER INFORMATION#(lf)    c.CustomerKey,#(lf)    c.FirstName,#(lf)    c.LastName,#(lf)    CONCAT(c.FirstName, ' ', c.LastName) AS FullName, -- Creating a calculated column#(lf)    c.EmailAddress,#(lf)    c.YearlyIncome,#(lf)    c.EnglishOccupation AS Occupation,#(lf)    c.EnglishEducation AS Education,#(lf)    #(lf)    -- 3. PRODUCT INFORMATION#(lf)    p.ProductKey,#(lf)    p.EnglishProductName AS ProductName,#(lf)    p.Color,#(lf)    p.Size,#(lf)    p.ListPrice,#(lf)    p.StandardCost,#(lf)    (p.ListPrice - p.StandardCost) AS ProfitPerUnit, -- Another calculated column#(lf)    #(lf)    -- 4. PRODUCT CATEGORIES (Corrected Section!)#(lf)    -- We join to two new tables to get this hierarchy#(lf)    subcat.EnglishProductSubcategoryName AS Subcategory,#(lf)    cat.EnglishProductCategoryName AS Category,#(lf)    #(lf)    -- 5. DATE INFORMATION (For Time Intelligence in PBI)#(lf)    d.FullDateAlternateKey AS FullDate,#(lf)    d.EnglishDayNameOfWeek AS DayOfWeek,#(lf)    d.EnglishMonthName AS MonthName,#(lf)    d.CalendarQuarter AS Quarter,#(lf)    d.CalendarYear AS [Year],#(lf)    #(lf)    -- 6. SALES TERRITORY (The region of the salesperson)#(lf)    st.SalesTerritoryRegion AS Region,#(lf)    st.SalesTerritoryCountry AS Country,#(lf)    st.SalesTerritoryGroup AS [Group],#(lf)    #(lf)    -- 7. CUSTOMER GEOGRAPHY (Where the customer lives)#(lf)    g.EnglishCountryRegionName AS CustomerCountry,#(lf)    g.StateProvinceName AS CustomerState,#(lf)    g.City AS CustomerCity#(lf)    #(lf)FROM #(lf)    -- Start with the main fact table. All queries begin here.#(lf)    [dbo].[FactInternetSales] fis#(lf)    #(lf)    -- Connect each sale to the customer who made it#(lf)    INNER JOIN [dbo].[DimCustomer] c #(lf)        ON fis.CustomerKey = c.CustomerKey#(lf)        #(lf)    -- Connect each sale to the product that was sold#(lf)    INNER JOIN [dbo].[DimProduct] p #(lf)        ON fis.ProductKey = p.ProductKey#(lf)        #(lf)    -- *** THE CRITICAL CORRECTION ***#(lf)    -- A product has a subcategory (e.g., ""Mountain Bikes""), but that subcategory is in a different table.#(lf)    -- We use a LEFT JOIN because not all products may have a subcategory assigned.#(lf)    LEFT JOIN [dbo].[DimProductSubcategory] subcat #(lf)        ON p.ProductSubcategoryKey = subcat.ProductSubcategoryKey#(lf)        #(lf)    -- A subcategory belongs to a category (e.g., ""Bikes""). This is in yet another table.#(lf)    -- We join from the subcategory table we just joined.#(lf)    LEFT JOIN [dbo].[DimProductCategory] cat #(lf)        ON subcat.ProductCategoryKey = cat.ProductCategoryKey#(lf)    -- *** END CORRECTION ***#(lf)        #(lf)    -- Connect the sale date to the full date table for time intelligence#(lf)    INNER JOIN [dbo].[DimDate] d #(lf)        ON fis.OrderDateKey = d.DateKey#(lf)        #(lf)    -- Connect to the sales territory (e.g., ""Northwest"", ""Canada"")#(lf)    INNER JOIN [dbo].[DimSalesTerritory] st #(lf)        ON fis.SalesTerritoryKey = st.SalesTerritoryKey#(lf)        #(lf)    -- Connect the customer to their geographical location#(lf)    INNER JOIN [dbo].[DimGeography] g #(lf)       ON c.GeographyKey = g.GeographyKey#(lf)#(lf)-- Optional: Filter for a specific year to keep the data size manageable for learning#(lf)-- WHERE d.CalendarYear = 2013#(lf)#(lf)-- Order the results by the most recent orders first#(lf)ORDER BY fis.OrderDate DESC;"]),
				    #"Split Column by Position" = Table.SplitColumn(Table.TransformColumnTypes(Source, {{"OrderDate", type text}}, "en-AU"), "OrderDate", Splitter.SplitTextByPositions({0, 11}, true), {"OrderDate.1", "OrderDate.2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Position",{{"OrderDate.1", type date}, {"OrderDate.2", type time}}),
				    #"Split Column by Position1" = Table.SplitColumn(Table.TransformColumnTypes(#"Changed Type", {{"DueDate", type text}}, "en-AU"), "DueDate", Splitter.SplitTextByPositions({0, 11}, true), {"DueDate.1", "DueDate.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Position1",{{"DueDate.1", type date}, {"DueDate.2", type time}}),
				    #"Split Column by Position2" = Table.SplitColumn(Table.TransformColumnTypes(#"Changed Type1", {{"ShipDate", type text}}, "en-AU"), "ShipDate", Splitter.SplitTextByPositions({0, 11}, true), {"ShipDate.1", "ShipDate.2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Position2",{{"ShipDate.1", type date}, {"ShipDate.2", type time}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type2",{"ShipDate.2", "DueDate.2", "OrderDate.2"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Columns",{{"YearlyIncome", Currency.Type}, {"ListPrice", Currency.Type}, {"StandardCost", Currency.Type}, {"ProfitPerUnit", Currency.Type}}),
				    #"Split Column by Position3" = Table.SplitColumn(Table.TransformColumnTypes(#"Changed Type3", {{"FullDate", type text}}, "en-AU"), "FullDate", Splitter.SplitTextByPositions({0, 11}, true), {"FullDate.1", "FullDate.2"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Position3",{{"FullDate.1", type date}, {"FullDate.2", type time}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type4",{"FullDate.2"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"FullDate.1", "FullDate"}}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Renamed Columns",{{"UnitPrice", type number}, {"SalesAmount", type number}, {"TaxAmt", type number}, {"ProfitPerUnit", type number}, {"StandardCost", type number}, {"ListPrice", type number}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type5",{{"ShipDate.1", "ShipDate"}, {"DueDate.1", "DueDate"}, {"OrderDate.1", "OrderDate"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

